language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - '5.5'
  - '5.6'
  - '7.0'

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.6.1 WP_MULTISITE=0

matrix:
  include:
    - php: '5.3'
      env: WP_VERSION=latest WP_MULTISITE=1
  exclude:
    - php: '7.0'
      env: WP_VERSION=4.2 WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install
  - vendor/bin/phpcs

script: phpunit
